spring:
  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:security_module_db}
    username: ${DB_USERNAME:miracle}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

audit:
  jwt:
    service:
      enabled: true
  feign:
    client:
      url: ${AUDIT_FEIGN_CLIENT_URL:http://localhost:8083}

security:
  session:
    client:
      enabled: true
  feign:
    client:
      url: ${SECURITY_FEIGN_CLIENT_URL:http://localhost:8080}

server:
  servlet:
    context-path: /security

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem