server:
  servlet:
    context-path: /overflow/questions
  port: 8082

spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:markoverflowDB}
    username: ${DB_USERNAME:miracle}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  feign:
    client:
      url: ${SECURITY_FEIGN_CLIENT_URL:localhost:8080}
  filters:
    session:
      enabled: true
    user:
      enabled: true

audit:
  jwt:
    service:
      enabled: true
  feign:
    client:
      url: ${AUDIT_FEIGN_CLIENT_URL:http://localhost:8083}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem