server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:audit_db}
    username: ${DB_USERNAME:miracle}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

audit:
  feign:
    client:
      url: ${AUDIT_FEIGN_CLIENT_URL:http://localhost:8083}

security:
  jwt:
    service:
      enabled: true
  feign:
    client:
      url: ${SECURITY_FEIGN_CLIENT_URL:http://localhost:8080}
  filters:
    root:
      enabled: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem